# The URL the site will be built for
base_url = "https://u9h.design"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "newsletter"

[extra]
[extra.newsletter]
cms = true
logo = "/media/default_logo.png"
menu = [ 
    # {url = "/blog", name = "Newsletter"},
    {url = "mailto:alex@u9h.design", name = "Contact"}
]

[extra.newsletter.home]
header = "More than just design."
subheader = "We are a fully-digital studio committed to creatives."
people = [
    { name = "Alexander Lozada", image = "alexander.jpg", position = "Founder", location = "Fort Worth, TX" },
    { name = "Christopher Wood", image = "chris.jpg", position = "Composition", location = "Pittsburgh, PA" },
    { name = "Jason Shultz", image = "jason.jpg", position = "Animation", location = "Rochester, NY" },
    { name = "Marisha Lozada", image = "default.svg", position = "Illustration", location = "New York, NY" },
    # { name = "Jack Kaiser", image = "default.svg", position = "Design", location = "Charlottesville, VA" },
    { name = "Kori Webster", image = "default.svg", position = "Agent", location = "Fort Worth, TX" },
]

[extra.newsletter.blog]
nav_background = "/media/default_pattern"
adwords_code = "ca-pub-9155129248808225"
menu = [
]