# The URL the site will be built for
base_url = "https://u9h.design"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "newsletter"

[extra]
[extra.newsletter]
cms = true
logo = "/media/default_logo.png"
menu = [ 
    # {url = "/blog", name = "Newsletter"},
    {url = "mailto:alex@u9h.design", name = "Contact"}
]

[extra.newsletter.home]
header = "More than just design."
subheader = "We are a fully-digital studio committed to creatives."
people = [
    { name = "Alexander Lozada", image = "alexander.jpg", position = "Founder", location = "Fort Worth, TX" },
    { name = "Christopher Wood", image = "chris.jpg", position = "Composition", location = "Pittsburgh, PA" },
    { name = "Jason Shultz", image = "jason.jpg", position = "Animation", location = "Rochester, NY" },
    { name = "Marisha Lozada", image = "default.svg", position = "Illustration", location = "New York, NY" },
    # { name = "Jack Kaiser", image = "default.svg", position = "Design", location = "Charlottesville, VA" },
    { name = "Kori Webster", image = "default.svg", position = "Agent", location = "Fort Worth, TX" },
]

[extra.newsletter.blog]
nav_background = "/media/default_pattern"
adwords_code = "ca-pub-9155129248808225"
mailchimp_embed = "<div id='mc_embed_signup'><form action='https://design.us19.list-manage.com/subscribe/post?u=7d95c50d4419888f846703410&amp;id=de6298b77b' method='post' id='mc-embedded-subscribe-form' name='mc-embedded-subscribe-form' class='validate' target='_blank' novalidate><div id='mc_embed_signup_scroll'><div class='mc-field-group'><label for='mce-EMAIL'>Email Address </label><input type='email' value='' name='EMAIL' class='required email' id='mce-EMAIL'></div><div id='mce-responses' class='clear'><div class='response' id='mce-error-response' style='display:none'></div><div class='response' id='mce-success-response' style='display:none'></div></div><div style='position: absolute; left: -5000px;' aria-hidden='true'><input type='text' name='b_7d95c50d4419888f846703410_de6298b77b' tabindex='-1' value=''></div><div class='clear'><input type='submit' value='Subscribe' name='subscribe' id='mc-embedded-subscribe' class='button'></div></div></form></div>"
disqus_url = "u9h.disqus.com"
menu = [
]
